// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCLEtfWmnkAm7-gnIfJXOlyWlqoWorjFwU',
    appId: '1:721052018724:web:e7719c099037629e9890b1',
    messagingSenderId: '721052018724',
    projectId: 'todo-d9b9f',
    authDomain: 'todo-d9b9f.firebaseapp.com',
    storageBucket: 'todo-d9b9f.firebasestorage.app',
    measurementId: 'G-85MRQ9V40B',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAGiw9YkE0Jpm0S_cvIKTEi3J_R9cMvR74',
    appId: '1:721052018724:android:995f4b72fe4516689890b1',
    messagingSenderId: '721052018724',
    projectId: 'todo-d9b9f',
    storageBucket: 'todo-d9b9f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD4z27uwpoVeTAcrMb_O25tRq0Yj8zUQNQ',
    appId: '1:721052018724:ios:f5ef82e4aa97decd9890b1',
    messagingSenderId: '721052018724',
    projectId: 'todo-d9b9f',
    storageBucket: 'todo-d9b9f.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD4z27uwpoVeTAcrMb_O25tRq0Yj8zUQNQ',
    appId: '1:721052018724:ios:f5ef82e4aa97decd9890b1',
    messagingSenderId: '721052018724',
    projectId: 'todo-d9b9f',
    storageBucket: 'todo-d9b9f.firebasestorage.app',
    iosBundleId: 'com.example.todoApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCLEtfWmnkAm7-gnIfJXOlyWlqoWorjFwU',
    appId: '1:721052018724:web:3d91c2cc91bd8c749890b1',
    messagingSenderId: '721052018724',
    projectId: 'todo-d9b9f',
    authDomain: 'todo-d9b9f.firebaseapp.com',
    storageBucket: 'todo-d9b9f.firebasestorage.app',
    measurementId: 'G-6W98P9FSBV',
  );
}
